name: Wen-Hao Lue
pygments: true
relative_permalinks: false
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

google_analytics:
  account: UA-12654814-1
disqus:
  id: wlue

# plugin
assets:
  compress:
    js: uglifier
    css: sass
